Models/Cinema.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace test3.Models
{
    public class Cinema
    {
        [Key]
        public int Id {get;set;}
        [Display(Name = "Cinema Logo")]
        [Required(ErrorMessage = "Logo is required")]
        public string? Logo {get;set;}

        [Display(Name = "Cinema Name")]
        [Required(ErrorMessage = "Full Name is required")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "Full Name must be between 3 and 100 chars")]  

        public string? FullName {get;set;}

        [Display(Name = "Discription")]
        [Required(ErrorMessage = "Discription is required")]
        public string? Discription {get;set;}

        // Relationship
        public List<Movie>? movies {get;set;}
    }
}

Controllers/CinemaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using test3.Areas.Identity.Data;
using test3.Models;
namespace test3.Controllers
{
    // [Route("[controller]")]
    public class CinemaController : Controller
    {

        private readonly test3IdentityDbContext _context;

        public CinemaController(test3IdentityDbContext context)
        {
            _context = context;

        }

        public async Task<IActionResult> Index()
        {
            var allCinmas = await _context.Cinemas.ToListAsync();
            return View(allCinmas);
        }
        // Get:Cinema/Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        // post:Cinema/Create
        public async Task<IActionResult> Create(Cinema obj)
        {
            if (!ModelState.IsValid)
            {
                return View(obj);
            }
            await  _context.AddAsync(obj);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        // Get:Cinema/Edit/id
        public IActionResult Details(int? id)
        {
            if(id == null || id==0) return NotFound();
            var viewCinema = _context.Cinemas.ToList().FirstOrDefault(d=>d.Id == id);
            if(viewCinema == null) return NotFound();
            return View(viewCinema);
        }

        // Get:Cinema/Edit/id
        public IActionResult Edit(int? id)
        {
            if(id == null || id==0) return NotFound();
            var viewCinema = _context.Cinemas.Find(id);
            if(viewCinema == null) return NotFound();
            return View(viewCinema);
        }
        [HttpPost]
        // post:Cinema/Edit/id
        public async Task<IActionResult> Edit(int? id,Cinema obj)
        {
            if (!ModelState.IsValid)
            {
                return View(obj);
            }
            _context.Update(obj);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        // Get:Cinema/Delete/id
        public IActionResult Delete(int? id)
        {
            if(id == null || id==0) return NotFound();
            var viewCinema = _context.Cinemas.Find(id);
            if(viewCinema == null) return NotFound();
            return View(viewCinema);
        }
        [HttpPost]
        // post:Cinema/Delete/id
        public async Task<IActionResult> DeletePost(int? id)
        {
            if(id == null || id==0) return NotFound();
            var viewCinema = _context.Cinemas.Find(id);
            if(viewCinema == null) return NotFound();
            _context.Remove(viewCinema);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Cinema/Create.cshtml
@model test3.Models.Cinema

@{
    ViewData["Title"] = "Add a new  Cinemas";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Add a New  Cinema</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create" asp-controller="Cinema" method="post">

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="LogoPicturePreview"  class="border-info rounded-circle" style="max-width: 150px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Logo" class="control-label" name="Logo">Logo</label>
                        <input asp-for="Logo" class="form-control" name="Logo" placeholder="Logo"/>
                        <span asp-validation-for="Logo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label" name="FullName">Name</label>
                        <input asp-for="FullName" class="form-control"  name="FullName" placeholder="FullName"/>
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label  asp-for="Discription" class="control-label" name="Discription">Discription</label>
                        <input  asp-for="Discription" class="form-control" name="Discription" Discription="Discription"/>
                        <span  asp-validation-for="Discription" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input  type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{ 
    <script>

        $(document).ready(function () {
            var output = document.getElementById('LogoPicturePreview');
            output.src = $("#Logo").val();
        })

        $("#Logo").on("change", function () {
            var output = document.getElementById('LogoPicturePreview');
            output.src = $(this).val();
        })
    </script>
}

Views/Cinema/Delete.cshtml
@model test3.Models.Cinema

@{
    ViewData["Title"] = "Delete confirmation for Cinema";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Delete for @Model.FullName </h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div >

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="LogoPicturePreview"  class="border-info rounded-circle" style="max-width: 150px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Logo" class="control-label" name="Logo" readonly >Logo</label>
                        <input asp-for="Logo" class="form-control" name="Logo" placeholder="Logo" readonly />
                        <span asp-validation-for="Logo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label" name="FullName" readonly >Name</label>
                        <input asp-for="FullName" class="form-control"  name="FullName" placeholder="FullName" readonly />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label  asp-for="Discription" class="control-label" name="Discription" readonly >Discription</label>
                        <input  asp-for="Discription" class="form-control" name="Discription" placeholder="Discription" readonly />
                        <span  asp-validation-for="Discription" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <form asp-action="DeletePost">
                            <input type="hidden" asp-for="Id" />
                            <input type="submit" value="Confirm" class="btn btn-danger float-right" />
                        </form>
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{ 
    <script>

        $(document).ready(function () {
            var output = document.getElementById('LogoPicturePreview');
            output.src = $("#Logo").val();
        })

    </script>
}

Views/Cinema/Details.cshtml
@model test3.Models.Cinema

@{
    ViewData["Title"] = "Details for Cinema";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Details for @Model.FullName </h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div >

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="LogoPicturePreview"  class="border-info rounded-circle" style="max-width: 150px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Logo" class="control-label" name="Logo" readonly >Logo</label>
                        <input asp-for="Logo" class="form-control" name="Logo" placeholder="Logo" readonly />
                        <span asp-validation-for="Logo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label" name="FullName" readonly >Name</label>
                        <input asp-for="FullName" class="form-control"  name="FullName" placeholder="FullName" readonly />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label  asp-for="Discription" class="control-label" name="Discription" readonly >Discription</label>
                        <input  asp-for="Discription" class="form-control" name="Discription" placeholder="Discription" readonly />
                        <span  asp-validation-for="Discription" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input  type="submit" value="Edit" class="btn btn-outline-success float-right" onclick="location.href='@Url.Action("Edit", "Cinema" ,  new {id=Model.Id })'" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{ 
    <script>

        $(document).ready(function () {
            var output = document.getElementById('LogoPicturePreview');
            output.src = $("#Logo").val();
        })

    </script>
}

Views/Cinema/Edit.cshtml
@model test3.Models.Cinema

@{
    ViewData["Title"] = "Edit Cinema";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Edit Cinema</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit" asp-controller="Cinema" method="post">

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview"  class="border-info rounded-circle" style="max-width: 150px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="Logo" class="control-label" name="Logo"> Logo</label>
                        <input asp-for="Logo" class="form-control" name="Logo" placeholder="Logo"/>
                        <span asp-validation-for="Logo" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label" name="FullName">Name</label>
                        <input asp-for="FullName" class="form-control"  name="FullName" placeholder="FullName"/>
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label  asp-for="Discription" class="control-label" name="Discription">Discriptiongraphy</label>
                        <input  asp-for="Discription" class="form-control" name="Discription" placeholder="Discription"/>
                        <span  asp-validation-for="Discription" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input  type="submit" value="Edit" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{ 
    <script>

        $(document).ready(function () {
            var output = document.getElementById('LogoPicturePreview');
            output.src = $("#Logo").val();
        })

    </script>
}

Views/Cinema/Index.cshtml
@model IEnumerable<test3.Models.Cinema>

@{
    ViewData["Title"] = "List of Cinemas";
}

<div class="row">
    <div class="col-md-8 offset-md-2">

        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.Logo)</th>
                    <th>@Html.DisplayNameFor(model => model.FullName)</th>
                    <th>@Html.DisplayNameFor(model => model.Discription)</th>
                    @* @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    { *@
                        <th>Actions</th>
                    @* } *@
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td class="align-middle">
                        <img class="rounded-circle" src="@item.Logo" alt="@item.FullName" style="max-width: 150px" />
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.FullName)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.Discription)
                    </td>
                    @* @if (User.Identity.IsAuthenticated && User.IsInRole("Admin")) *@
                    @* { *@
                        <td class="align-middle">
                            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit </a> |
                            <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details </a> |
                            <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete </a>
                        </td>
                    @* } *@

                </tr>
                }
            </tbody>

        </table>

    </div>
    <div style="position: fixed; left: 90%;  botton:50px; top:90%;">
        <button  class="btn  btn-infoCreate" type="submit" onclick="location.href='@Url.Action("Create", "Cinema")'">
            <i class="bi bi-patch-plus"></i>Add new</button>
    </div
</div>