Controllers/ActorController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using test3.Areas.Identity.Data;
using test3.Models;
using Microsoft.AspNetCore.Authorization;

namespace test3.Controllers
{
    // [Route("[controller]")]
    public class ActorController : Controller
    {
        private readonly test3IdentityDbContext _context;

        public ActorController(test3IdentityDbContext context)
        {
            _context = context;

        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allActors = await _context.Actors.ToListAsync();
            return View(allActors);
        }

        // Get:Actor/Create
        public IActionResult Create()
        {
            // IEnumerable<Actor> viewActors = _context.Actors.ToList();
            return View();
        }
        [HttpPost]
        // post:Actor/Create
        public async Task<IActionResult> Create(Actor obj)
        {
            if (!ModelState.IsValid)
            {
                // Console.WriteLine(obj.FullName + " "+ obj.Bio+" "+obj.ProfilePictureURL+" "+obj.Id+obj.actor_Movies);
                return View(obj);
            }
            await  _context.AddAsync(obj);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        // Get:Actor/Edit/id
        public IActionResult Details(int? id)
        {
            if(id == null || id==0) return NotFound();
            var ViewActor = _context.Actors.ToList().FirstOrDefault(d=>d.Id == id);
            if(ViewActor == null) return NotFound();
            // IEnumerable<Actor> viewActors = _context.Actors.ToList();
            return View(ViewActor);
        }

        // Get:Actor/Edit/id
        public IActionResult Edit(int? id)
        {
            if(id == null || id==0) return NotFound();
            var ViewActor = _context.Actors.Find(id);
            if(ViewActor == null) return NotFound();
            // IEnumerable<Actor> viewActors = _context.Actors.ToList();
            return View(ViewActor);
        }
        [HttpPost]
        // post:Actor/Edit/id
        public async Task<IActionResult> Edit(int? id,Actor obj)
        {
            if (!ModelState.IsValid)
            {
                // Console.WriteLine(obj.FullName + " "+ obj.Bio+" "+obj.ProfilePictureURL+" "+obj.Id+obj.actor_Movies);
                return View(obj);
            }
            _context.Update(obj);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
                // Get:Actor/Delete/id
        public IActionResult Delete(int? id)
        {
            if(id == null || id==0) return NotFound();
            var ViewActor = _context.Actors.Find(id);
            if(ViewActor == null) return NotFound();
            // IEnumerable<Actor> viewActors = _context.Actors.ToList();
            return View(ViewActor);
        }
        [HttpPost]
        // post:Actor/Delete/id
        public async Task<IActionResult> DeletePost(int? id)
        {
            if(id == null || id==0) return NotFound();
            var ViewActor = _context.Actors.Find(id);
            if(ViewActor == null) return NotFound();
            _context.Remove(ViewActor);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/MovieController.cs
using System.Net;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using test3.Models;
using test3.Areas.Identity.Data;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace test3.Controllers
{
    public class MovieController :Controller 
    {
        private readonly test3IdentityDbContext _db;
        public  MovieController(test3IdentityDbContext db){
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            var allMovies = await _db.Movies.Include(a=>a.cinema).ToListAsync();
            return View(allMovies);
        }

        public async Task<IActionResult> Filter(string searchString) //searchString is name box search in file _loginpartial.html
        {
            var allMovies = await _db.Movies.Include(a=>a.cinema).ToListAsync();
            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResult = allMovies.Where(n => n.Name.ToLower().Contains(searchString.ToLower()) 
                || n.Description.ToLower().Contains(searchString.ToLower())).ToList();

                // var filteredResultNew = allMovies.Where(n => 
                // string.Equals(n.Name, searchString, StringComparison.CurrentCultureIgnoreCase) ||
                // string.Equals(n.Description, searchString, StringComparison.CurrentCultureIgnoreCase)).ToList();

                return View("Index", filteredResult);
            }

            return View("Index",allMovies);
        }
        // Get
        // Get:Movie/Create
        public async Task<IActionResult> Create()
        {
            var response = new NewMovieDropdownsVM(){
            Actors = await _db.Actors.OrderBy(n=>n.FullName).ToListAsync(),
            Producers = await _db.Producers.OrderBy(n=>n.FullName).ToListAsync(),
            Cinemas = await _db.Cinemas.OrderBy(n=>n.FullName).ToListAsync()
            };

            ViewBag.CinemaViewBag = new SelectList(response.Cinemas , "Id" ,"FullName");
            ViewBag.ProducerViewBag = new SelectList(response.Producers , "Id" ,"FullName");
            ViewBag.ActorViewBag = new SelectList(response.Actors , "Id" ,"FullName");

            return View();
        }
        [HttpPost]
        // post:Movie/Create
        public async Task<IActionResult> Create(NewMovieVM obj)
        {
            if (!ModelState.IsValid)
            {
                var response = new NewMovieDropdownsVM(){
                Actors = await _db.Actors.OrderBy(n=>n.FullName).ToListAsync(),
                Producers = await _db.Producers.OrderBy(n=>n.FullName).ToListAsync(),
                Cinemas = await _db.Cinemas.OrderBy(n=>n.FullName).ToListAsync()
                };

                ViewBag.CinemaViewBag = new SelectList(response.Cinemas , "Id" ,"FullName");
                ViewBag.ProducerViewBag = new SelectList(response.Producers , "Id" ,"FullName");
                ViewBag.ActorViewBag = new SelectList(response.Actors , "Id" ,"FullName");
                return View(obj);
            }
            var newMovie = new Movie(){
                Name = obj.Name,
                Description = obj.Description,
                Price = obj.Price,
                ImageURL = obj.ImageURL,
                StartDate = obj.StartDate,
                EndDate = obj.EndDate,
                MovieCategory =obj.MovieCategory,
                producerId = obj.ProducerId,
                CinemaId =obj.CinemaId
            };
            await  _db.Movies.AddAsync(newMovie);
            await _db.SaveChangesAsync();
            // Relationship
            foreach (var item in obj.ActorId)
            {
                var newActorMovie = new  Actor_Movie(){
                    MovieId = newMovie.Id,
                    ActorId = item
                };
                await  _db.Actors_Movies.AddAsync(newActorMovie);
            }
            
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        // Get:Movie/Edit/id
        public IActionResult Details(int? id)
        {
            if(id == null || id==0) return NotFound();
            var ViewMovie = _db.Movies.Include(c=>c.cinema).
            Include(p=>p.producer)
            .Include(am=>am.actor_Movies).ThenInclude(a=>a.actor)
            .ToList().FirstOrDefault(d=>d.Id == id);
            if(ViewMovie == null) return NotFound();
            // IEnumerable<Movie> viewMovies = _db.Movies.ToList();
            return View(ViewMovie);
        }

        // Get:Movie/Edit/id
        public async Task<IActionResult> Edit(int? id)
        {
            if(id == null || id==0) return NotFound();
            var ViewMovie = _db.Movies.Include(c=>c.cinema).
            Include(p=>p.producer)
            .Include(am=>am.actor_Movies).ThenInclude(a=>a.actor)
            .ToList().FirstOrDefault(d=>d.Id == id);
            if(ViewMovie == null) return NotFound();
            var newMovie = new NewMovieVM(){
                Id = ViewMovie.Id,
                Name = ViewMovie.Name,
                Description = ViewMovie.Description,
                Price = ViewMovie.Price,
                ImageURL = ViewMovie.ImageURL,
                StartDate = ViewMovie.StartDate,
                EndDate = ViewMovie.EndDate,
                MovieCategory =ViewMovie.MovieCategory,
                ProducerId = ViewMovie.producerId,
                CinemaId =ViewMovie.CinemaId,
                ActorId = ViewMovie.actor_Movies.Select(Am=>Am.ActorId).ToList()
            };
            var response = new NewMovieDropdownsVM(){
            Actors = await _db.Actors.OrderBy(n=>n.FullName).ToListAsync(),
            Producers = await _db.Producers.OrderBy(n=>n.FullName).ToListAsync(),
            Cinemas = await _db.Cinemas.OrderBy(n=>n.FullName).ToListAsync()
            };

            ViewBag.CinemaViewBag = new SelectList(response.Cinemas , "Id" ,"FullName");
            ViewBag.ProducerViewBag = new SelectList(response.Producers , "Id" ,"FullName");
            ViewBag.ActorViewBag = new SelectList(response.Actors , "Id" ,"FullName");

            return View(newMovie);
        }
        [HttpPost]
        // post:Movie/Edit
        public async Task<IActionResult> Edit(int? id,NewMovieVM obj)
        {
            if(id == null || id==0) return NotFound();
            var ViewMovie = _db.Movies.Include(c=>c.cinema).
            Include(p=>p.producer)
            .Include(am=>am.actor_Movies).ThenInclude(a=>a.actor)
            .ToList().FirstOrDefault(d=>d.Id == id);
            if(ViewMovie == null) return NotFound();
            if (!ModelState.IsValid)
            {
                var response = new NewMovieDropdownsVM(){
                Actors = await _db.Actors.OrderBy(n=>n.FullName).ToListAsync(),
                Producers = await _db.Producers.OrderBy(n=>n.FullName).ToListAsync(),
                Cinemas = await _db.Cinemas.OrderBy(n=>n.FullName).ToListAsync()
                };

                ViewBag.CinemaViewBag = new SelectList(response.Cinemas , "Id" ,"FullName");
                ViewBag.ProducerViewBag = new SelectList(response.Producers , "Id" ,"FullName");
                ViewBag.ActorViewBag = new SelectList(response.Actors , "Id" ,"FullName");
                return View(obj);
            }
            
            ViewMovie.Name = obj.Name;
            ViewMovie.Description = obj.Description;
            ViewMovie.Price = obj.Price;
            ViewMovie.ImageURL = obj.ImageURL;
            ViewMovie.StartDate = obj.StartDate;
            ViewMovie.EndDate = obj.EndDate;
            ViewMovie.MovieCategory =obj.MovieCategory;
            ViewMovie.producerId = obj.ProducerId;
            ViewMovie.CinemaId =obj.CinemaId;
            
            await _db.SaveChangesAsync();

            var existActors = _db.Actors_Movies.Where(n=>n.MovieId == obj.Id).ToList();
            _db.Actors_Movies.RemoveRange(existActors);
            await _db.SaveChangesAsync();
            // Relationship
            foreach (var item in obj.ActorId)
            {
                var newActorMovie = new  Actor_Movie(){
                    MovieId = obj.Id,
                    ActorId = item
                };
                await  _db.Actors_Movies.AddAsync(newActorMovie);
            }
            
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        // Get:Movie/Delete/id
        // public IActionResult Delete(int? id)
        // {
        //     if(id == null || id==0) return NotFound();
        //     var ViewMovie = _db.Movies.Find(id);
        //     if(ViewMovie == null) return NotFound();
        //     // IEnumerable<Movie> viewMovies = _db.Movies.ToList();
        //     return View(ViewMovie);
        // }
        // [HttpPost]
        // // post:Movie/Delete/id
        // public async Task<IActionResult> DeletePost(int? id)
        // {
        //     if(id == null || id==0) return NotFound();
        //     var ViewMovie = _db.Movies.Find(id);
        //     if(ViewMovie == null) return NotFound();
        //     _db.Remove(ViewMovie);
        //     await _db.SaveChangesAsync();
        //     return RedirectToAction("Index");
        // }
       
       
    }
}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using test3.Areas.Identity.Data;
using test3.Models;
using test3.Areas.Identity.Data.Cart;
using System.Security.Claims;

namespace test3.Controllers
{
    // [Route("[controller]")]
    public class OrderController : Controller
    {
        private readonly ShoppingCart _shoppingCart;
        private readonly test3IdentityDbContext _db;
        public OrderController(ShoppingCart shoppingCart,test3IdentityDbContext db )
        {
            _shoppingCart = shoppingCart;
            _db = db;
        }
        public async Task StoreOrderAsync(List<ShoppingCartItem> items, string userId, string userEmailAddress)
        {
            var order = new Order()
            {
                UserId = userId,
                Email = userEmailAddress
            };
            await _db.Orders.AddAsync(order);
            await _db.SaveChangesAsync();

            foreach (var item in items)
            {
                var orderItem = new OrderItem()
                {
                    Amount = item.Amount,
                    MovieId = item.Movie.Id,
                    OrderId = order.Id,
                    Price = item.Movie.Price
                };
                await _db.orderItems.AddAsync(orderItem);
            }
            await _db.SaveChangesAsync();
        }
    
        public async Task<List<Order>> GetOrdersByUserIdAndRoleAsync(string userid)
        {
            var orders = await _db.Orders.Include(n => n.OrderItems)
            .ThenInclude(n => n.Movie).Where(n => n.UserId == userid).ToListAsync();

            // if(userRole != "Admin")
            // {
            //     orders = orders.Where(n => n.UserId == userId).ToList();
            // }

            return orders;
        }
        public async Task<IActionResult> Index()
        {
            string userId = "";
            // string userRole = "";

            var orders = await GetOrdersByUserIdAndRoleAsync(userId);
            return View(orders);
        }
        public async Task<IActionResult> ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            var response = new ShoppingCartVM(){
                ShoppingCart = _shoppingCart ,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }
        
        public async Task<RedirectToActionResult> AddItemToShoppingCart(int id){
            var item = await _db.Movies
                .Include(c => c.cinema)
                .Include(p => p.producer)
                .Include(am => am.actor_Movies).ThenInclude(a => a.actor)
                .FirstOrDefaultAsync(n => n.Id == id);
            if(item != null){
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));

        }
        
        
        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _db.Movies
                .Include(c => c.cinema)
                .Include(p => p.producer)
                .Include(am => am.actor_Movies).ThenInclude(a => a.actor)
                .FirstOrDefaultAsync(n => n.Id == id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = "";
            string userEmailAddress = "";

            // await StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Movie/Details.cshtml
@model test3.Models.Movie

@{
    ViewData["Title"] = "Details for Movie";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-TbMovie">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageURL" width="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                        <p class="card-text">
                            <b>Cinema: </b>
                            <a asp-controller="Cinema" asp-action="Details" asp-route-id="@Model.CinemaId">
                                @Model.cinema.FullName
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Producer: </b>
                            <a asp-controller="Producer" asp-action="Details" asp-route-id="@Model.producerId">
                                @Model.producer.FullName
                            </a>
                        </p>
                        <p class="card-text"><b>Category: </b>@Model.MovieCategory</p>
                        <p class="card-text"><b>Start Date: </b>@Model.StartDate.ToString("dd MMM yy")</p>
                        <p class="card-text"><b>End Date: </b>@Model.EndDate.ToString("dd MMM yy")</p>
                        <p class="card-text ">
                            <b>Status: </b>
                            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                            {
                                <span class="badge bg-success text-white">AVAILABLE</span>
                            }
                            else if (DateTime.Now > Model.EndDate)
                            {
                                <span class="badge bg-danger text-white">EXPIRED</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">UPCOMING</span>
                            }
                        </p>
                        <p class="card-text">
                            <b>Actors: </b>
                            <hr />
                            <div class="row">
                                @foreach (var actor in Model.actor_Movies)
                                {
                                    <div class="column text-center">
                                        <img class="border-info rounded-circle" src="@actor.actor.ProfilePictureURL" style="max-width: 150px" />
                                        <br />
                                        <a asp-controller="Actor" asp-action="Details" asp-route-id="@actor.ActorId">@actor.actor.Id</a>
                                    </div>
                                }
                            </div>
                        </p>

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                Back to List
                            </a>
                            <a class="btn btn-success text-white  @((DateTime.Now > Model.EndDate) ? "disabled" : "")"  onclick="location.href='@Url.Action("AddItemToShoppingCart", "Order" ,  new {id=@Model.Id })'" >
                               <i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c") )</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Movie/Index.cshtml
@model IEnumerable<test3.Models.Movie>

@{
    ViewData["Title"] = "List of Movies";
}
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-TbMovie">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                    @* @if (User.Identity.IsAuthenticated && User.IsInRole("Admin")) *@
                                    @* { *@
                                        <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                    @* } *@
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageURL" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><b>Cinema: </b>@item.cinema.FullName</p>
                            <p class="card-text"><b>Category: </b>@item.MovieCategory</p>
                            <p class="card-text"><b>Start Date: </b>@item.StartDate</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDate</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-DTMovie float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                                <a class="btn btn-success text-white" onclick="location.href='@Url.Action("AddItemToShoppingCart", "Order" ,  new {id=item.Id })'" >
                                <i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    <div style="position: fixed; left: 90%;  botton:50px; top:90%;" class="float-right">
        <button  class="btn btn-infoCreate" type="submit" onclick="location.href='@Url.Action("Create", "Movie")'">
            <i class="bi bi-patch-plus"></i>Add new</button>
    </div>
</div>

@* @await Html.PartialAsync("_CreateItem", "Movies")  *@

Views/Movie/List.cshtml
@model IEnumerable<test3.Models.Movie>
<h2 class="display-4">Movies</h2>

<button class="btn btn-primary" type="submit" onclick="location.href='@Url.Action("Create", "Movie")'">NewMovie</button>

<table class="table">
  <tr>
    <th>Movie</th>
    <th>Genre</th>
  </tr>
  @foreach (var item in Model)
  {
    <tr>
        @* <td ><a href="#link" asp-asp-controller="Home" asp-action="Index" asp-route-id="@item.Id">@item.Name</a></td> *@
        <td ><a href="@Url.Action("Edit","Movie" , new { id = item.Id })" >@item.Name</a></td>
        <td>@item.MovieCategory</td>
    </tr>
  }

</table>

Views/Movie/Random.cshtml
@{
    ViewData["Title"] = "Random";
}
@model test3.Models.Movie
<h2> @Model.Name </h2>


Views/Movie/onlyReadList.cshtml
@model IEnumerable<test3.Models.Movie>
<h2 class="display-4">Movies</h2>

@* <button class="btn btn-primary" type="submit" onclick="location.href='@Url.Action("Create", "Movie")'">NewMovie</button> *@

<table class="table">
  <tr>
    <th>Movie</th>
    <th>Genre</th>
  </tr>
  @foreach (var item in Model)
  {
    <tr>
        @* <td ><a href="#link" asp-asp-controller="Home" asp-action="Index" asp-route-id="@item.Id">@item.Name</a></td> *@
        <td>@item.Name</td>
        <td>@item.MovieCategory</td>
    </tr>
  }

</table>