Models/Producer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace test3.Models
{
    public class Producer
    {
        [Key]
        public int Id {get;set;}
        [Display(Name = "Profile Picture")]
        [Required(ErrorMessage = "Profile Picture is required")]
        public string? ProfilePictureURL {get;set;}

        [Display(Name = "FullName")]
        [Required(ErrorMessage = "Full Name is required")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "Full Name must be between 3 and 100 chars")]  

        public string? FullName {get;set;}
        
        [Display(Name = "Biography")]
        [Required(ErrorMessage = "Biography is required")]
        public string? Bio {get;set;}

        // Relationship
        public List<Movie>? movies {get;set;}
    }
}

Controllers/ProducerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using test3.Areas.Identity.Data;
using test3.Models;
namespace test3.Controllers
{
    // [Route("[controller]")]
    public class ProducerController : Controller
    {
        private readonly test3IdentityDbContext _context;

        public ProducerController(test3IdentityDbContext context)
        {
            _context = context;

        }

        public async Task<IActionResult> Index()
        {
            var allProducers = await _context.Producers.ToListAsync();
            return View(allProducers);
        }
        // Get:Producer/Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        // post: Producer/Create
        public async Task<IActionResult> Create( Producer obj)
        {
            if (!ModelState.IsValid)
            {
                return View(obj);
            }
            await  _context.AddAsync(obj);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        // Get: Producer/Edit/id
        public IActionResult Details(int? id)
        {
            if(id == null || id==0) return NotFound();
            var viewProducer = _context. Producers.ToList().FirstOrDefault(d=>d.Id == id);
            if(viewProducer == null) return NotFound();
            return View(viewProducer);
        }

        // Get: Producer/Edit/id
        public IActionResult Edit(int? id)
        {
            if(id == null || id==0) return NotFound();
            var viewProducer = _context. Producers.Find(id);
            if(viewProducer == null) return NotFound();
            return View(viewProducer);
        }
        [HttpPost]
        // post: Producer/Edit/id
        public async Task<IActionResult> Edit(int? id, Producer obj)
        {
            if (!ModelState.IsValid)
            {
                return View(obj);
            }
            _context.Update(obj);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        // Get: Producer/Delete/id
        public IActionResult Delete(int? id)
        {
            if(id == null || id==0) return NotFound();
            var viewProducer = _context. Producers.Find(id);
            if(viewProducer == null) return NotFound();
            return View(viewProducer);
        }
        [HttpPost]
        // post: Producer/Delete/id
        public async Task<IActionResult> DeletePost(int? id)
        {
            if(id == null || id==0) return NotFound();
            var viewProducer = _context. Producers.Find(id);
            if(viewProducer == null) return NotFound();
            _context.Remove(viewProducer);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Producer/Create.cshtml
@model test3.Models.Producer

@{
    ViewData["Title"] = "Add a new Producers";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Add a New Producer</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create" asp-controller="Producer" method="post">

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview"  class="border-info rounded-circle" style="max-width: 150px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePictureURL" class="control-label" name="ProfilePictureURL">ProfilePictureURL</label>
                        <input asp-for="ProfilePictureURL" class="form-control" name="ProfilePictureURL" placeholder="ProfilePictureURL"/>
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label" name="FullName">Name</label>
                        <input asp-for="FullName" class="form-control"  name="FullName" placeholder="FullName"/>
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label  asp-for="Bio" class="control-label" name="Bio">Biography</label>
                        <input  asp-for="Bio" class="form-control" name="Bio" placeholder="Bio"/>
                        <span  asp-validation-for="Bio" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input  type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{ 
    <script>

        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();
        })

        $("#ProfilePictureURL").on("change", function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $(this).val();
        })
    </script>
}

Views/Producer/Delete.cshtml
@model test3.Models.Producer

@{
    ViewData["Title"] = "Delete confirmation for Producer";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Delete for @Model.FullName </h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div >

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview"  class="border-info rounded-circle" style="max-width: 150px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePictureURL" class="control-label" name="ProfilePictureURL" readonly >ProfilePictureURL</label>
                        <input asp-for="ProfilePictureURL" class="form-control" name="ProfilePictureURL" placeholder="ProfilePictureURL" readonly />
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label" name="FullName" readonly >Name</label>
                        <input asp-for="FullName" class="form-control"  name="FullName" placeholder="FullName" readonly />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label  asp-for="Bio" class="control-label" name="Bio" readonly >Biography</label>
                        <input  asp-for="Bio" class="form-control" name="Bio" placeholder="Bio" readonly />
                        <span  asp-validation-for="Bio" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <form asp-action="DeletePost">
                            <input type="hidden" asp-for="Id" />
                            <input type="submit" value="Confirm" class="btn btn-danger float-right" />
                        </form>
                        @* <input  type="submit" value="confirm" class="btn btn-outline-success float-right" /> *@
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{ 
    <script>

        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();
        })

    </script>
}

Views/Producer/Details.cshtml
@model test3.Models.Producer

@{
    ViewData["Title"] = "Details for Producer";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Details for @Model.FullName </h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div >

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview"  class="border-info rounded-circle" style="max-width: 150px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePictureURL" class="control-label" name="ProfilePictureURL" readonly >ProfilePictureURL</label>
                        <input asp-for="ProfilePictureURL" class="form-control" name="ProfilePictureURL" placeholder="ProfilePictureURL" readonly />
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label" name="FullName" readonly >Name</label>
                        <input asp-for="FullName" class="form-control"  name="FullName" placeholder="FullName" readonly />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label  asp-for="Bio" class="control-label" name="Bio" readonly >Biography</label>
                        <input  asp-for="Bio" class="form-control" name="Bio" placeholder="Bio" readonly />
                        <span  asp-validation-for="Bio" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input  type="submit" value="Edit" class="btn btn-outline-success float-right" onclick="location.href='@Url.Action("Edit", "Producer" ,  new {id=Model.Id })'" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{ 
    <script>

        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();
        })

    </script>
}

Views/Producer/Edit.cshtml
@model test3.Models.Producer

@{
    ViewData["Title"] = "Edit Producer";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Edit Producer</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit" asp-controller="Producer" method="post">

                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-center">
                        <img id="ProfilePicturePreview"  class="border-info rounded-circle" style="max-width: 150px" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePictureURL" class="control-label" name="ProfilePictureURL">ProfilePictureURL</label>
                        <input asp-for="ProfilePictureURL" class="form-control" name="ProfilePictureURL" placeholder="ProfilePictureURL"/>
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-label" name="FullName">Name</label>
                        <input asp-for="FullName" class="form-control"  name="FullName" placeholder="FullName"/>
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label  asp-for="Bio" class="control-label" name="Bio">Biography</label>
                        <input  asp-for="Bio" class="form-control" name="Bio" placeholder="Bio"/>
                        <span  asp-validation-for="Bio" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input  type="submit" value="Edit" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{ 
    <script>

        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();
        })

    </script>
}

Views/Producer/Index.cshtml
@model IEnumerable<test3.Models.Producer>

@{
    ViewData["Title"] = "List of Producers";
}

<div class="row">
    <div class="col-md-8 offset-md-2">

        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.ProfilePictureURL)</th>
                    <th>@Html.DisplayNameFor(model => model.FullName)</th>
                    <th>@Html.DisplayNameFor(model => model.Bio)</th>
                    @* @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    { *@
                        <th>Actions</th>
                    @* } *@
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td class="align-middle">
                        <img class="rounded-circle" src="@item.ProfilePictureURL" alt="@item.FullName" style="max-width: 150px" />
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.FullName)
                    </td>
                    <td class="align-middle">
                        @Html.DisplayFor(modelItem => item.Bio)
                    </td>
                    @* @if (User.Identity.IsAuthenticated && User.IsInRole("Admin")) *@
                    @* { *@
                        <td class="align-middle">
                            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit </a> |
                            <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details </a> |
                            <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="bi bi-trash"></i>Delete </a>
                        </td>
                    @* } *@

                </tr>
                }
            </tbody>

        </table>

    </div>
    <div style="position: fixed;left: 90%;  botton:50px; top:90%;">
        <button  class="btn  btn-infoCreate" type="submit" onclick="location.href='@Url.Action("Create", "Producer")'">
            <i class="bi bi-patch-plus"></i>Add new Producer</button>
    </div
</div>